version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - "db"
  db:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_PASS
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'  # Corrigido para usar a porta diretamente

volumes:
  db:
